// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhCoach.Infra.Persistence;

#nullable disable

namespace MinhCoach.Infra.Migrations
{
    [DbContext(typeof(MindCoachDbContext))]
    [Migration("20250224031618_addTablesForTaskandUserManagementToDb")]
    partial class addTablesForTaskandUserManagementToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MinhCoach.Domain.SubTask.SubTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('Task', 'SubTask', 'TemplateTask')")
                        .HasDefaultValue("SubTask");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("SubTasks", (string)null);
                });

            modelBuilder.Entity("MinhCoach.Domain.Task.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('Low', 'Medium', 'High')")
                        .HasDefaultValue("Medium");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('Task', 'SubTask', 'TemplateTask')")
                        .HasDefaultValue("Task");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("MinhCoach.Domain.Template.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPrivateTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("MinhCoach.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("/images/users/default-user.png");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MinhCoach.Domain.SubTask.SubTask", b =>
                {
                    b.HasOne("MinhCoach.Domain.Task.Task", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MinhCoach.Domain.Common.ValueObjects.TaskDetail", "TaskDetail", b1 =>
                        {
                            b1.Property<Guid>("SubTaskId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Description")
                                .HasColumnType("longtext")
                                .HasColumnName("Description");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("EndTime");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("StartTime");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("ENUM('Todo', 'Inprogress', 'Done')")
                                .HasDefaultValue("Todo")
                                .HasColumnName("Status");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("SubTaskId");

                            b1.ToTable("SubTasks");

                            b1.WithOwner()
                                .HasForeignKey("SubTaskId");
                        });

                    b.OwnsOne("MinhCoach.Domain.Common.ValueObjects.FullTimestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("SubTaskId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("CreatedAt");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("DeletedAt");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("UpdatedAt");

                            b1.HasKey("SubTaskId");

                            b1.ToTable("SubTasks");

                            b1.WithOwner()
                                .HasForeignKey("SubTaskId");
                        });

                    b.Navigation("TaskDetail")
                        .IsRequired();

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("MinhCoach.Domain.Task.Task", b =>
                {
                    b.HasOne("MinhCoach.Domain.Template.Template", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TemplateId");

                    b.OwnsOne("MinhCoach.Domain.Common.ValueObjects.TaskDetail", "TaskDetail", b1 =>
                        {
                            b1.Property<Guid>("TaskId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Description")
                                .HasColumnType("longtext")
                                .HasColumnName("Description");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("EndTime");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("StartTime");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("ENUM('Todo', 'Inprogress', 'Done')")
                                .HasDefaultValue("Todo")
                                .HasColumnName("Status");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("TaskId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskId");
                        });

                    b.OwnsOne("MinhCoach.Domain.Common.ValueObjects.FullTimestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("TaskId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("CreatedAt");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("DeletedAt");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("UpdatedAt");

                            b1.HasKey("TaskId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskId");
                        });

                    b.Navigation("TaskDetail")
                        .IsRequired();

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("MinhCoach.Domain.Template.Template", b =>
                {
                    b.OwnsOne("MinhCoach.Domain.Common.ValueObjects.FullTimestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("CreatedAt");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("DeletedAt");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("UpdatedAt");

                            b1.HasKey("TemplateId");

                            b1.ToTable("Templates");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("MinhCoach.Domain.User.User", b =>
                {
                    b.OwnsOne("MinhCoach.Domain.Common.ValueObjects.FullTimestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("CreatedAt");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("DeletedAt");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("UpdatedAt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("MinhCoach.Domain.Task.Task", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("MinhCoach.Domain.Template.Template", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
